### PR TITLE
(MODULES-1830) Updated passenger-conf.erb to include Passenger 5 when setti...

### PR DESCRIPTION
**Pull request by mattkamsler**
...ng PassengerEnabled on and not implementing RailsAutoDetect On.

### CODE REVIEW

**Comment by mattkamsler** [comment]
Commit message should have said "Updated to include Passenger 5" not "Puppet 5" I attempted to change the message to avoid confusion.

**Comment by gauthier-delacroix** [comment]
Shouldn't you check that major version is >= 4, instead of fixing it to 4-5 ? That would avoid the wait for an update on v6 release.

**Comment by ghoneycutt** [comment]
@gauthier-delacroix +1 since the README does not say that it supports a specific version of passenger.

**Comment by mattkamsler** [comment]
After thinking about it more I agree with @gauthier-delacroix and @ghoneycutt.  Originally I was thinking that it should be looked at again on an upgrade, but in reality it should be tested anytime you change the version anyways.  There isn't any reason to force a code change every time the version changes - which is the situation that required this change in the first place.  I will make the change to be "greater than" when I get a few minutes.  Thank you for the feedback!

**Comment by DavidS** [comment]
I've changed to code as discussed to allow all later versions at #88

**Pull request closed without merging**
